# Generated by Django 5.0.1 on 2024-03-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default=None, max_length=200)),
                ('album', models.CharField(default=None, max_length=100)),
                ('audio', models.FileField(blank=True, default=None, null=True, upload_to='audio/files')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='thumbnail/images')),
                ('title', models.CharField(default=None, max_length=100)),
                ('category', models.CharField(default=None, max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('demo', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
    ]
